config/routes.rb
Rails.application.routes.draw do
  resources :logins
  resources :developers
  resources :projects
  resources :time_entries

  root 'logins#dashboard'

end

app/models/developer.rb
class Developer < ActiveRecord::Base
  has_secure_password
  has_many :time_entries, :dependent => :restrict_with_error
  validates :name, :email, :password, presence: true
  validates :email, uniqueness: true

  def total_hours
    weekly_hours = 0
    start_day = Time.now.beginning_of_week
    end_day = Time.now.end_of_week
    self.time_entries.each do |t|
      if t.worked_on >= start_day && t.worked_on <= end_day
        weekly_hours += t.duration
      end
    end
    weekly_hours
  end

  def overtime?
    total_hours > 40
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :time_entries, :dependent => :restrict_with_error
  validates :max_hours, :name, presence: true
  validates :name, uniqueness: true

  def total_hours
    all_hours = []
    time_entries.all.each do |t|
      all_hours << t.duration
    end
    all_hours.reduce(:+)
  end

  def maxed_out_time_budget?
    if self.total_hours == nil || self.total_hours < max_hours
      return false
    else
      return true
    end
  end
end

app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
  belongs_to :developer
  belongs_to :project
  validates :duration, :worked_on, :developer, :project, presence: true
  validates :duration, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= Developer.find_by_id(session[:developer_id])
  end

  def logged_in?
    if current_user.nil?
      redirect_to new_login_path
    end
  end
  
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?
  before_action :developer_match?, only: [:edit, :update, :destroy]

  def index
    @developers = Developer.all
  end

  def new
    @developer = Developer.new
  end

  def create
    @developer = Developer.new(developer_params)
    if @developer.save
      redirect_to developers_path, notice: 'Developer was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @developer.update(developer_params)
      redirect_to developers_path, notice: 'Developer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @developer.destroy
      redirect_to developers_path, notice: 'Developer was successfully deleted.'
    else
      redirect_to developers_path, notice: 'You cannot delete this developer due to their associated records.'
    end
  end

  private

  def set_developer
    @developer = Developer.find(params[:id])
  end

  def developer_params
    params.require(:developer).permit(:name, :email, :password)
  end

  def developer_match?
    if current_user.id != @developer.id
      redirect_to developers_path, notice: 'You can only edit your own records.'
    end
  end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :logged_in?, except: [:new, :create]

  def new
  end

  def dashboard
    @time_entries = current_user.time_entries
  end

  def create
    if request.post?
      developer = Developer.find_by_email(params[:email])
      if developer && developer.authenticate(params[:password])
        session[:developer_id] = developer.id
        flash[:notice] = "Welcome!"
        redirect_to root_path
      else
        flash[:notice] = "Invalid e-mail or password."
        redirect_to new_login_path
      end
    end
  end


  def destroy
    session[:developer_id] = nil
    redirect_to new_login_path, notice: 'You have logged out.'
  end



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_path, notice: 'Project was successfully deleted.'
    else
      redirect_to projects_path, notice: 'You cannot delete this project due to its associated records.'
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :max_hours)
  end

end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  before_action :set_time_entry, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?
  before_action :developer_match?, only: [:edit, :update, :destroy]

  def index
    @time_entries = TimeEntry.all
  end

  def new
    @time_entry = TimeEntry.new
  end

  def create
    @time_entry = TimeEntry.new(time_entry_params)
    if @time_entry.save
      redirect_to root_path, notice: 'Time Entry was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @time_entry.update(time_entry_params)
      redirect_to root_path, notice: 'Time Entry was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @time_entry.destroy
    redirect_to root_path, notice: 'Time Entry was successfully deleted.'
  end

  private

  def set_time_entry
    @time_entry = TimeEntry.find(params[:id])
  end

  def time_entry_params
    params.require(:time_entry).permit(:duration, :worked_on, :developer_id, :project_id)
  end

  def developer_match?
    if current_user.id != @time_entry.developer_id
      redirect_to root_path, notice: 'You can only edit your own records.'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/developer_helper.rb
module DeveloperHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/time_entry_helper.rb
module TimeEntryHelper
end

app/views/developers/_form.html.erb
<%= form_for(@developer) do |f| %>
  <% if @developer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@developer.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
      <% @developer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <% if @developer.id == nil %>
    <div class="form-group">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save Developer", class: "btn btn-default"%>
  </div>
<% end %>

app/views/developers/edit.html.erb
<h1>Editing Developer</h1>

<%= render 'form' %>

<%= link_to 'Back', developers_path %>

app/views/developers/index.html.erb
<h2>Developers</h2>

<p><%= link_to 'New Developer', new_developer_path, id: "new-dev-link" %></p>

<table class = "table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Hours Worked This Week</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @developers.each do |developer| %>
      <tr class="<%= "warning" if developer.overtime? %>">
        <td><%= developer.name %></td>
        <td><%= developer.email %></td>
        <td><%= developer.total_hours %></td>

        <td class = "text-center"><%= link_to 'Edit', edit_developer_path(developer) %></td>
        <td class = "text-center"><%= link_to 'Delete', developer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/developers/new.html.erb
<h1>New Developer</h1>

<%= render 'form' %>

<%= link_to 'Back', developers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeveloperTimeTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= favicon_link_tag '/favicongit.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class = "container">

<% if session[:developer_id] %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="navbar-brand" href="#">Signed in as <%=@current_user.name%></span>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Dashboard', root_path, id: "go-to-root" %></li>
          <li><%= link_to 'Developers', developers_path, id: "dev-index-link" %></li>
          <li><%= link_to 'Projects', projects_path, id: "proj-index-link" %></li>
          <li><%= link_to 'Log Out', login_path(session[:developer_id]), method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>
<div class= "row">
  <div class="col-md-12">
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </div>
</div>
</div>
</body>
</html>

app/views/logins/_form.html.erb
<%= form_tag logins_path do %>
  <div class = "form-group">
    <%= label_tag :email %><br />
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class = "form-group">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class = "form-group"><%= submit_tag "Log in", class: "btn btn-default" %></div>
<% end %>

app/views/logins/create.html.erb
<h1>Login#create</h1>
<p>Find me in app/views/login/create.html.erb</p>

app/views/logins/dashboard.html.erb
<h2>Your Time Entries</h2>

<p><%= link_to 'New Time Entry', new_time_entry_path, id: "new-entry-link" %></p>

<% if @current_user.overtime? %>
<p id = "overtime-warning">WARNING: YOU ARE CURRENTLY IN OVERTIME FOR THE WEEK</p>
<% end %>

<table class= "table table-bordered">
  <thead>
    <tr>
      <th>Date Worked</th>
      <th>Duration</th>
      <th>Project</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @time_entries.each do |entry| %>
      <tr>
        <td><%= entry.worked_on %></td>
        <td><%= entry.duration %> hours</td>
        <td><%= entry.project.name %></td>

        <td class = "text-center"><%= link_to 'Edit', edit_time_entry_path(entry) %></td>
        <td class = "text-center"><%= link_to 'Delete', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/logins/new.html.erb
<h1>Log In</h1>

<%= render 'form' %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :max_hours %><br>
    <%= f.number_field :max_hours %>
  </div>

  <div class="form-group">
    <%= f.submit "Save Project", class: "btn btn-default"%>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h2>Projects</h2>

<p><%= link_to 'New Project', new_project_path, id: "new-proj-link" %></p>

<table class = "table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Max Hours Allowed</th>
      <th>Total Hours Worked</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr class="<%= "warning" if project.maxed_out_time_budget? %>">
        <td><%= project.name %></td>
        <td><%= project.max_hours %></td>
        <td><%= project.total_hours %></td>

        <td class = "text-center"><%= link_to 'Edit', edit_project_path(project) %></td>
        <td class = "text-center"><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/time_entries/_form.html.erb
<%= form_for(@time_entry) do |f| %>
  <% if @time_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_entry.errors.count, "error") %> prohibited this time_entry from being saved:</h2>

      <ul>
      <% @time_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="form-group">
    <%= f.label :worked_on %><br>
    <%= f.date_field :worked_on %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :developer_id, :value => current_user.id %>
  </div>
  <div class="form-group">
    <%= f.label :project_id %><br>
    <%= f.collection_select :project_id, Project.all, :id, :name, {:include_blank => ""} %>
  </div>

  <div class="form-group">
    <%= f.submit "Save Time Entry", class: "btn btn-default"%>
  </div>
<% end %>

app/views/time_entries/edit.html.erb
<h1>Editing Time Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/time_entries/new.html.erb
<h1>New Time Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>